[project]
name = "project-ai-ftsy-football-sum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.121.0",
    "gradio>=6.22.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "yt-dlp>=2026.7.4",
]
