apiVersion: v1
kind: Service
metadata:
  name: project-ai-ftsy-football-sum
  namespace: project-ai-ftsy-football-sum
spec:
  selector:
    app: project-ai-ftsy-football-sum
  ports:
    - protocol: TCP
      port: 3068
      targetPort: 7068
  type: NodePort