apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-ai-ftsy-football-sum-data
  namespace: project-ai-ftsy-football-sum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
