// Runs on the HOST, before the container is created, via initializeCommand.
//
// Its whole job is to write the machine-specific half of the devcontainer
// config into a gitignored .env that docker-compose.local.yml interpolates.
// Nothing here is committed except this script: no host paths, no identity,
// no secrets end up in git.
//
// Why this exists rather than the ${localEnv:USERPROFILE}${localEnv:HOME}
// concatenation: that trick assumes exactly one of the two variables is set.
// On a Windows host whose VS Code inherited a Git Bash environment BOTH are
// set, and the concatenation yields the two paths glued together - which
// Docker rejects with a syntax error that says nothing about where it came
// from. Resolving the home directory on the host, where the OS is known,
// cannot go wrong that way.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ENV_FILE = path.join(HERE, '.env');
const EXAMPLE_FILE = path.join(HERE, '.env.example');
const LOCAL_DIR = path.join(HERE, '.local');

const BEGIN = '# >>> devcontainer machine config - generated by bootstrap.mjs, do not edit >>>';
const END = '# <<< devcontainer machine config <<<';

// Compose treats a backslash as an escape; forward slashes work on every
// platform, Windows drive letters included.
const posix = (p) => p.split(String.fromCharCode(92)).join('/'); // 92 = backslash

function gitConfig(key) {
    try {
        return execFileSync('git', ['config', '--get', key], {
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim();
    } catch {
        return '';
    }
}

function placeholder(name, contents) {
    mkdirSync(LOCAL_DIR, { recursive: true });
    const p = path.join(LOCAL_DIR, name);
    if (contents === null) mkdirSync(p, { recursive: true });
    else if (!existsSync(p)) writeFileSync(p, contents);
    return p;
}

// A bind mount whose source does not exist is not skipped - Docker CREATES it,
// and for a file source you get a directory where a file should be. So every
// host-dependent path is resolved here and falls back to something real inside
// the gitignored .local/, rather than letting Docker invent things in a home
// directory that is not ours to write to.
function resolveClaudeDir(home) {
    const real = path.join(home, '.claude');
    if (existsSync(real)) return { path: real, present: true };
    return { path: placeholder('empty-claude', null), present: false };
}

// git's global ignore file. Without it the container reports untracked files
// the host does not, which shows up as a `git status` that fails parity for a
// reason that has nothing to do with the container. The default location is
// the XDG one; core.excludesFile overrides it.
function resolveGlobalExcludes(home) {
    const configured = gitConfig('core.excludesFile');
    const candidates = [];
    if (configured) {
        candidates.push(
            configured.startsWith('~/') ? path.join(home, configured.slice(2)) : configured,
        );
    }
    const xdg = process.env.XDG_CONFIG_HOME || path.join(home, '.config');
    candidates.push(path.join(xdg, 'git', 'ignore'));
    for (const c of candidates) {
        if (existsSync(c)) return { path: c, present: true };
    }
    return { path: placeholder('gitignore-global', ''), present: false };
}

const home = os.homedir();
const claude = resolveClaudeDir(home);
const excludes = resolveGlobalExcludes(home);

const values = {
    HOST_HOME: posix(home),
    HOST_CLAUDE_DIR: posix(claude.path),
    HOST_HAS_CLAUDE: claude.present ? '1' : '0',
    HOST_GIT_EXCLUDES: posix(excludes.path),
    // Apple Silicon needs linux/arm64; everything else here is amd64. The base
    // image is multi-arch, so this is the only place architecture is named.
    DOCKER_PLATFORM: os.arch() === 'arm64' ? 'linux/arm64' : 'linux/amd64',
    GIT_USER_NAME: gitConfig('user.name'),
    GIT_USER_EMAIL: gitConfig('user.email'),
};

// Seed from the example so a fresh clone gets the shape of what it needs, then
// keep whatever the user hand-edited outside the marked block.
let existing = '';
if (existsSync(ENV_FILE)) existing = readFileSync(ENV_FILE, 'utf8');
else if (existsSync(EXAMPLE_FILE)) existing = readFileSync(EXAMPLE_FILE, 'utf8');

// Cut out any previous generated block, wherever it sits, so re-running
// replaces it rather than appending a second copy.
const beginIdx = existing.indexOf(BEGIN);
if (beginIdx !== -1) {
    const endIdx = existing.indexOf(END, beginIdx);
    existing = endIdx === -1
        ? existing.slice(0, beginIdx)
        : existing.slice(0, beginIdx) + existing.slice(endIdx + END.length);
}
existing = existing.trimEnd();

// Written LAST, and with LF regardless of the surrounding file's endings: a
// trailing carriage return on HOST_HOME corrupts every volume path derived
// from it, and compose's dotenv parser lets the final assignment of a key win.
const block = [
    BEGIN,
    ...Object.entries(values).map(([k, v]) => `${k}=${v}`),
    END,
    '',
].join('\n');

writeFileSync(ENV_FILE, (existing ? existing + '\n\n' : '') + block, 'utf8');

console.log(`devcontainer: wrote ${posix(path.relative(process.cwd(), ENV_FILE))}`);
console.log(`  host home     ${values.HOST_HOME}`);
console.log(`  platform      ${values.DOCKER_PLATFORM}`);
console.log(`  git identity  ${values.GIT_USER_NAME || '(unset)'} <${values.GIT_USER_EMAIL || '(unset)'}>`);
console.log(`  git excludes  ${excludes.present ? values.HOST_GIT_EXCLUDES : '(host has none - using an empty placeholder)'}`);
if (!claude.present) {
    // Informational, not a warning: someone without Claude Code installed is
    // not in a broken state, and the container starts fine.
    console.log('  ~/.claude was not found on this host - mounting an empty placeholder.');
    console.log('  Install Claude Code on the host and re-create the container to share skills and auth.');
}
