name: Build and Deploy

on:
  push:
    branches:
      - feat/tr/2026-updates # Triggers whenever you push to main from Windows or Mac
  workflow_dispatch: # Allows you to manually trigger the workflow and select a branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Allows the action to push to GHCR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ffsum:latest